name: ShellCheck
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Run ShellCheck
      uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1.32.0
      with:
        level: warning
        fail_level: none
        filter_mode: nofilter
        exclude: |
          ./vendor/*
          ./release-tools/*
          ./hack/*
        shellcheck_flags: --external-sources -e SC2034
